const P={legs:'https://crossbar-gym.com/pages/beine-workout',chest:'https://crossbar-gym.com/pages/brust-workout',back:'https://crossbar-gym.com/pages/rucken-workout',shoulder:'https://crossbar-gym.com/pages/schulter-workout',biceps:'https://crossbar-gym.com/pages/bizeps-workout',triceps:'https://crossbar-gym.com/pages/trizeps-workout',anchor:'https://crossbar-gym.com/pages/verwendung-turanker'};
const BAND_SIDE_KG={'Weiß':4.5,'Rot':6.8,'Grün':11.3,'Blau':22.5};
const BAND_OPTIONS=['','Weiß','Rot','Grün','Blau','Weiß + Rot','Grün + Weiß','Grün + Rot','Blau + Weiß','Blau + Rot','Blau + Grün','Blau + Grün + Weiß','Blau + Grün + Rot','Alle 4'];
const DAYS=['So','Mo','Di','Mi','Do','Fr','Sa'];
const A=['squat','push','row','press','curl','tri','core'],B=['dead','chest','lat','rev','front','hammer','tri2'];
const MAIN=new Set(['squat','push','row','press','dead','chest','lat']);
const E={
 squat:{name:'Kniebeuge – Stange in der Ellenbeuge',short:'Kniebeuge',muscle:'Beine · Gesäß',page:'legs',reps:[8,15],start:'Aus deinen Daten: Grün war klar zu leicht. Als nächstes Grün + Weiß testen.',official:'Beine – Squats – Fixierung der Stange in der Ellenbeuge',setup:['Band mittig unter beide Füße.','Füße schulterbreit, Spitzen leicht außen.','Crossbar sicher in der Ellenbeuge; Bauch fest.'],cues:['Hüfte nach hinten/unten.','Knie folgen den Fußspitzen.','Fersen unten, kontrolliert hoch.'],error:'Knie nicht nach innen; Rücken nicht rund.'},
 push:{name:'Liegestütze – Standardgriff',short:'Liegestütze',muscle:'Brust · Trizeps · Core',page:'chest',reps:[8,15],start:'Noch kein Zusatzband. Im ersten Training war Satz 2 bereits RIR 0.',official:'Brust – Liegestütze – Standard Griff',setup:['Crossbar/Docks nach offiziellem Clip.','Körper als stabile Linie.','Bauch und Gesäß fest.'],cues:['Brust kontrolliert absenken.','Ellbogen nicht 90° seitlich.','Boden aktiv wegdrücken.'],error:'Nicht bis zum Technikverlust erzwingen.'},
 row:{name:'Rudern – sitzend',short:'Rudern sitzend',muscle:'Rücken · Bizeps',page:'back',reps:[8,15],start:'Aus deinen Daten: Blau 15/15 bei RIR 4+. Als nächstes Blau + Weiß testen.',official:'Rücken – Rudern – sitzend',setup:['Brust aufrichten.','Schultern tief.','Arme lang starten.'],cues:['Stange Richtung Bauch.','Schulterblätter zusammen.','2–3 s zurück.'],error:'Nicht aus dem unteren Rücken reißen.'},
 press:{name:'Schulterdrücken',short:'Schulterdrücken',muscle:'Schulter · Trizeps',page:'shoulder',reps:[8,15],start:'Grün beibehalten. 15/15 bei RIR 2/1 passt gut.',official:'Schulter – Schulterdrücken',setup:['Band unter beide Füße.','Stange auf Schulterhöhe.','Bauch und Gesäß fest.'],cues:['Über Kopf drücken.','Rippen unten halten.','Langsam zurück.'],error:'Kein starkes Hohlkreuz.'},
 curl:{name:'Bizeps – enger Griff – Curl',short:'Bizeps enger Griff',muscle:'Bizeps',page:'biceps',reps:[10,12],start:'Fortgeschrittenen-Vorschlag aus deinem Crossbar-Clip: 11,3 + 4,5 kg je Seite = Grün + Weiß.',official:'Bizeps – enger Griff – Curl',setup:['Die engen Griffpositionen der Crossbar verwenden.','Ellenbogen dicht am Körper.','Aufrecht stehen.'],cues:['Kontrolliert hochcurlen.','Oben kurz anspannen.','Langsam ablassen.'],error:'Nicht aus Hüfte oder Rücken schwingen.'},
 tri:{name:'French Press – enger Griff',short:'French Press eng',muscle:'Trizeps',page:'triceps',reps:[10,15],start:'Grün ist aktuell ein sinnvoller Arbeitswiderstand.',official:'Trizeps – French press – enger Griff',setup:['Engen Griff nach offiziellem Clip verwenden.','Oberarme stabil.','Bauch fest.'],cues:['Ellenbogen strecken.','Oben anspannen.','Kontrolliert zurück.'],error:'Nicht mit dem Oberkörper wippen.'},
 core:{name:'Beinzug – Beine & Bauch',short:'Beinzug Core',muscle:'Core · Hüftbeuger',page:'legs',reps:[12,20],start:'Rot beibehalten; 15/15 bei RIR 2 passt.',official:'Beine 2 – Beine und Bauch Beinzug',setup:['Fußschlaufen sicher.','Rumpf stabil.','Clip zuerst ansehen.'],cues:['Bein(e) heranziehen.','Becken stabil.','Langsam zurück.'],error:'Kein Schwung.'},
 dead:{name:'Sumo Deadlift',short:'Sumo Deadlift',muscle:'Gesäß · hintere Kette',page:'legs',reps:[8,15],start:'Erster Test: Grün; als Fortgeschrittener bei RIR >3 direkt Kombination erwägen.',official:'Sumo Deadlift',setup:['Breiter Stand.','Stange dicht am Körper.','Rücken neutral.'],cues:['Hüfte zurück/unten.','Boden wegdrücken.','Oben aufrecht.'],error:'Nicht rund ziehen.'},
 chest:{name:'Brustdrücken – Türanker',short:'Brustdrücken Türanker',muscle:'Brust · Trizeps',page:'chest',reps:[8,15],start:'Erster Test: Grün oder Grün + Weiß; technisch sauber kalibrieren.',official:'Brust – Drücken mit Türanker',setup:['Türanker sicher montieren.','Anker hinter dir auf Brusthöhe.','Versetzter Stand.'],cues:['Nach vorn drücken.','Schultern tief.','Langsam zurück.'],error:'Tür und Zugrichtung vorher prüfen.'},
 lat:{name:'Latzug – Türanker oben',short:'Latzug Türanker',muscle:'Lat · Rücken · Bizeps',page:'back',reps:[8,15],start:'Erster Test: Grün; bei RIR >3 Kombination erhöhen.',official:'Rücken – Latzug',setup:['Türanker oben.','Stabil knien/sitzen.','Brust leicht anheben.'],cues:['Ellbogen Richtung Rippen.','Kontrolliert ziehen.','Langsam hochlassen.'],error:'Nicht nach hinten reißen.'},
 rev:{name:'Reverse Butterfly',short:'Reverse Butterfly',muscle:'Hintere Schulter · Rücken',page:'back',reps:[12,20],start:'Leichter beginnen; hier zählt saubere Schulterblattkontrolle.',official:'Rücken – Butterfly reverse',setup:['Rumpf stabil.','Nacken lang.','Arme kontrolliert führen.'],cues:['Arme außen/hinten.','Schulterblätter zusammen.','Langsam zurück.'],error:'Lieber leichter als schwingen.'},
 front:{name:'Schulter – Frontziehen',short:'Frontziehen',muscle:'Schulter · oberer Rücken',page:'shoulder',reps:[10,15],start:'Erster Test: Weiß + Rot oder Grün – nach RIR kalibrieren.',official:'Schulter – Frontziehen',setup:['Band unter Füßen.','Stange vor dem Körper.','Bauch fest.'],cues:['Kontrolliert hochziehen.','Ellbogen führen.','Langsam absenken.'],error:'Nicht mit Schwung.'},
 hammer:{name:'Hammer Curl – parallel/einzeln',short:'Hammer Curl',muscle:'Bizeps · Unterarm',page:'biceps',reps:[10,15],start:'Mit Handgriffen neutral greifen; Widerstand nach 1–2 RIR wählen.',official:'Bizeps – Hammer Curl – parallel/einzeln',setup:['Neutraler Griff.','Ellenbogen nah.','Rumpf ruhig.'],cues:['Hochcurlen.','Kurz halten.','Langsam ablassen.'],error:'Ellenbogen nicht vorziehen.'},
 tri2:{name:'Trizeps – Drücken stehend',short:'Trizeps Drücken',muscle:'Trizeps',page:'triceps',reps:[10,15],start:'Widerstand so wählen, dass 1–2 RIR bleiben.',official:'Trizeps – Drücken – stehend',setup:['Aufbau nach Clip.','Oberarme stabil.','Bauch fest.'],cues:['Strecken.','Kurz anspannen.','Kontrolliert zurück.'],error:'Kein Schwung.'}
};
function bandParts(s){if(!s)return[];if(s==='Alle 4')return['Weiß','Rot','Grün','Blau'];return s.split('+').map(x=>x.trim()).filter(x=>BAND_SIDE_KG[x])}
function bandSideKg(s){return bandParts(s).reduce((a,b)=>a+BAND_SIDE_KG[b],0)}
function bandTotalKg(s){return bandSideKg(s)*2}
function bandLabel(s){if(!s)return'ohne Band / Körpergewicht';return `${s} · ca. ${bandSideKg(s).toFixed(1).replace('.',',')} kg je Seite / ${bandTotalKg(s).toFixed(1).replace('.',',')} kg nominal gesamt`}
function def(){return{week:1,logs:[],draft:{},prs:{},ready:{energy:3,sleep:3,sore:3},settings:{days:[1,3,5],level:'advanced'}}}
let S;try{S=JSON.parse(localStorage.getItem('crossbarCoachAzureGlassTestV1')||'null')||def()}catch(e){S=def()}
S.settings=S.settings||{};S.settings.days=Array.isArray(S.settings.days)&&S.settings.days.length?S.settings.days:[1,3,5];S.settings.level=S.settings.level||'advanced';S.logs=S.logs||[];S.draft=S.draft||{};S.prs=S.prs||{};S.ready=S.ready||{energy:3,sleep:3,sore:3};
function doneSet(x){return !!(x&&(x.done===true||(x.done===undefined&&x.reps)))}
function save(){localStorage.setItem('crossbarCoachAzureGlassTestV1',JSON.stringify(S));stats()}
function ph(w){if(w===1)return['Kalibrierung',2,2,90,'Fortgeschritten im Krafttraining, Crossbar neu: 2 Sätze zum Kalibrieren, meist 1–2 RIR; bei neuer Technik 2–3.'];if(w===2)return['Technik & Aufbau',3,2,90,'Grundübungen 3 Sätze, Isolationsübungen 2; meist 1–2 RIR.'];if(w<=4)return['Volumen aufbauen',3,3,90,'3 Arbeitssätze; sauber im Zielbereich arbeiten.'];if(w<=7)return['Progression',3,3,105,'Erst Wiederholungen, dann Widerstand bzw. Bandkombination steigern.'];return['Entlastung',2,2,90,'Bewusst leichter, deutlich mehr Reserve.']}
function last(){return S.logs[0]?.workout||null}function nextWorkout(){return last()==='A'?'B':'A'}
function psets(id){let p=ph(S.week);return MAIN.has(id)?p[1]:p[2]}
function exComplete(key,sets){let a=S.draft[key]?.sets||[];return Array.from({length:sets},(_,i)=>doneSet(a[i])).every(Boolean)}
function bandOptions(selected){return BAND_OPTIONS.map(v=>`<option value="${v}" ${selected===v?'selected':''}>${v||'Band wählen'}</option>`).join('')}
function card(id,w,i,lib=false){let e=E[id],p=ph(S.week),sets=psets(id),key=S.week+'-'+w+'-'+id,d=S.draft[key]||{},rows='',complete=!lib&&exComplete(key,sets);if(!lib){for(let n=0;n<sets;n++){let x=d.sets?.[n]||{},dn=doneSet(x);rows+=`<div class="set"><b>${n+1}</b><input inputmode="numeric" placeholder="Wdh." value="${x.reps||''}" onchange="sd('${key}',${n},'reps',this.value)"><select onchange="sd('${key}',${n},'band',this.value);bandNote('${key}',${n},this.value)">${bandOptions(x.band||'')}</select><select onchange="sd('${key}',${n},'rir',this.value)">${['','0','1','2','3','4+'].map(v=>`<option value="${v}" ${x.rir===v?'selected':''}>${v===''?'RIR':v}</option>`).join('')}</select><input class="check" type="checkbox" ${dn?'checked':''} onchange="sd('${key}',${n},'done',this.checked);if(this.checked)openTimer(${p[3]})"></div><div class="loadnote" id="n-${key}-${n}">${x.band?bandLabel(x.band):''}</div>`}}
return`<details class="card exercise ${complete?'completed':''}" data-key="${key}" data-sets="${sets}"><summary><div><div class="exname">${i+1}. ${e.name}</div><div class="meta">${e.muscle} · ${lib?'<span class="variant">'+e.official+'</span>':sets+' Sätze · '+e.reps[0]+'–'+e.reps[1]+' Wdh.'}</div></div><span class="doneMark">${complete?'✓':'⌄'}</span></summary><div class="body"><div class="call"><b>Exakte Variante:</b> <span class="variant">${e.official}</span></div><div class="call ok"><b>Für dich:</b> ${e.start}</div><div class="grid two"><div><b>Aufbau</b><ol>${e.setup.map(x=>'<li>'+x+'</li>').join('')}</ol></div><div><b>Ausführung</b><ol>${e.cues.map(x=>'<li>'+x+'</li>').join('')}</ol></div></div><div class="call warn"><b>Fehler:</b> ${e.error}</div><div class="actions"><a class="btn" target="_blank" href="${P[e.page]}">🎥 Offizieller Übungsbereich</a>${['chest','lat'].includes(id)?`<a class="btn s" target="_blank" href="${P.anchor}">🚪 Türanker</a>`:''}</div>${lib?'':`<hr><div class="sethead"><span></span><span>Wdh.</span><span>Band/Kombi</span><span>RIR</span><span>✓</span></div><div class="sets">${rows}</div>`}</div></details>`}
function bandNote(k,n,v){let el=document.getElementById('n-'+k+'-'+n);if(el)el.textContent=v?bandLabel(v):''}
function sd(k,n,f,v){S.draft[k]??={sets:[]};S.draft[k].sets??=[];S.draft[k].sets[n]??={};S.draft[k].sets[n][f]=v;save();refreshCompletion()}
function refreshCompletion(){document.querySelectorAll('.exercise[data-key]').forEach(el=>{let c=exComplete(el.dataset.key,+el.dataset.sets);el.classList.toggle('completed',c);let m=el.querySelector('.doneMark');if(m)m.textContent=c?'✓':'⌄'})}
function renderWork(w){let ids=w==='A'?A:B,done=ids.filter(id=>exComplete(S.week+'-'+w+'-'+id,psets(id))).length,el=document.getElementById('work'+w);el.innerHTML=`<div class="card" style="margin-top:12px"><div class="kicker">Workout ${w}</div><h2>${w==='A'?'Basis & Druck':'Zug & Variation'}</h2><p class="muted"><b>${done}/${ids.length}</b> Übungen abgeschlossen. Grün = komplett erledigt.</p><button class="btn ok" onclick="finish('${w}')">✓ Einheit abschließen</button></div>`+ids.map((id,i)=>card(id,w,i)).join('')}
function showWorkout(w){workA.style.display=w==='A'?'block':'none';workB.style.display=w==='B'?'block':'none';tab('training')}
let pendingWorkout=null;function finish(w){pendingWorkout=w;finishTitle.textContent='Workout '+w;feelInput.value=3;feelVal.textContent=3;durationInput.value=60;finishModal.classList.add('show')}
function closeFinish(){finishModal.classList.remove('show');pendingWorkout=null}
feelInput.oninput=()=>feelVal.textContent=feelInput.value;
function confirmFinish(){let w=pendingWorkout;if(!w)return;let ids=w==='A'?A:B,entries={};ids.forEach(id=>entries[id]=S.draft[S.week+'-'+w+'-'+id]||{});S.logs.unshift({date:new Date().toISOString(),week:S.week,workout:w,entries,duration:+durationInput.value||0,feeling:+feelInput.value||3,readiness:{...S.ready}});rebuildPrs();save();closeFinish();render();alert('Workout gespeichert. Nächstes Mal ist automatisch Workout '+nextWorkout()+' dran.')}
function score(band,reps){return bandTotalKg(band)*100+(+reps||0)}
function rebuildPrs(){S.prs={};for(let l of [...S.logs].reverse()){for(let[id,en]of Object.entries(l.entries||{})){for(let x of en.sets||[]){if(!doneSet(x)||!x.reps)continue;let o=S.prs[id];if(!o||score(x.band,+x.reps)>score(o.band,o.reps))S.prs[id]={band:x.band||'',reps:+x.reps,date:l.date}}}}}
function readiness(){let e=+energy.value,s=+sleep.value,m=+sore.value;S.ready={energy:e,sleep:s,sore:m};ev.textContent=e;sv.textContent=s;mv.textContent=m;let z=Math.round((e+s+(6-m))/15*100);ready.className='call '+(z>=75?'ok':z>=55?'warn':'bad');ready.innerHTML='<b>'+z+'% bereit.</b> '+(z>=75?'Plan normal trainieren.':z>=55?'Konservativ starten und 2–3 RIR lassen.':'Heute eher Regeneration oder deutlich reduzieren.');save()}
function today(){let planned=S.settings.days.includes(new Date().getDay()),n=nextWorkout();todayTitle.textContent=planned?'Workout '+n:'Regeneration';todayText.textContent=planned?'Geplanter Krafttag. Nächstes Workout: '+n+'.':'Heute ist laut Wochenplan Ruhetag. Wenn du dich gut fühlst, kannst du trotzdem Workout '+n+' trainieren.';todayBtn.textContent=planned?'Workout '+n+' öffnen':'Workout '+n+' heute trainieren';todayBtn.onclick=()=>showWorkout(n);dayChip.textContent=S.settings.days.length+'× Kraft/Woche';levelChip.textContent=S.settings.level==='advanced'?'Fortgeschritten · Crossbar neu':'Einsteiger'}
function stats(){st1.textContent=S.logs.length;st2.textContent=S.logs.reduce((a,l)=>a+(l.duration||0),0)+' min';st3.textContent=Object.keys(S.prs).length;let c=S.logs.filter(l=>l.week===S.week).length;wp.style.width=Math.min(100,c/3*100)+'%';wpt.textContent=c+' Einheiten absolviert · Wochenziel 3';reportHint.innerHTML='Aktuell sind <b>'+S.logs.length+'</b> gespeicherte Einheiten für eine Auswertung vorhanden.'}
function latestSets(id){for(let l of S.logs){let ss=l.entries?.[id]?.sets?.filter(x=>doneSet(x)&&x.reps);if(ss?.length)return ss}return null}
function nextCombo(current){let s=BAND_OPTIONS.filter(Boolean).sort((a,b)=>bandTotalKg(a)-bandTotalKg(b)),kg=bandTotalKg(current);return s.find(x=>bandTotalKg(x)>kg+.1)||null}
function rec(){nextRec.textContent='Noch keine Trainingsdaten';nextRecText.textContent='Nach den ersten Einheiten bekommst du hier konkrete Progressionshinweise.';for(let id of [...A,...B]){let ss=latestSets(id),e=E[id];if(!ss)continue;let av=ss.reduce((a,x)=>a+(+x.reps),0)/ss.length,rr=ss.map(x=>x.rir==='4+'?4:+x.rir).filter(Number.isFinite),ar=rr.length?rr.reduce((a,b)=>a+b,0)/rr.length:null,band=ss.map(x=>x.band).filter(Boolean).at(-1)||'';nextRec.textContent=e.short;if(av>=e.reps[1]&&ar!==null&&ar>=2){let up=nextCombo(band);nextRecText.textContent=up?'Oberes Ende mit Reserve erreicht. Nächstes Mal '+up+' vorsichtig testen.':'Oberes Ende erreicht; Vorspannung oder schwierigere Variante erhöhen.'}else if(ar!==null&&ar<=.5)nextRecText.textContent='Sehr nah am Limit. Gleiches Setup behalten oder den ersten Satz etwas früher stoppen.';else nextRecText.textContent='Gleiches Setup behalten und zuerst innerhalb des Zielbereichs steigern.';return}}
function roadmap(){let current=[...S.logs].filter(l=>l.week===S.week).reverse(),completed=current.map(l=>l.workout).filter(x=>x==='A'||x==='B'),slots=completed.slice(0,3).map((w,i)=>({w,done:true,label:'Einheit '+(i+1)})),n=nextWorkout();while(slots.length<3){slots.push({w:n,done:false,label:'Einheit '+(slots.length+1)});n=n==='A'?'B':'A'}roadWeek.innerHTML=slots.map((x,i)=>`<div class="routeStep ${x.done?'done':(!x.done&&i===Math.min(completed.length,2)?'next':'')}"><span class="meta">${x.label}</span><b>${x.w}${x.done?' ✓':''}</b><span class="meta">${x.done?'erledigt':(i===Math.min(completed.length,2)?'als Nächstes':'danach')}</span></div>`).join('');roadNow.innerHTML='<b>Nächste Einheit: Workout '+nextWorkout()+'.</b> '+completed.length+' von 3 geplanten Einheiten in Woche '+S.week+' erledigt.';let phases=[['W1','Kalibrierung'],['W2–4','Aufbau'],['W5–7','Progression'],['W8','Entlastung']],active=S.week===1?0:S.week<=4?1:S.week<=7?2:3;phaseRoad.innerHTML=phases.map((x,i)=>`<div class="phaseBox ${i===active?'active':''}"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');allWeeks.innerHTML=Array.from({length:8},(_,i)=>{let w=i+1,start=w%2===1?'A':'B',seq=start==='A'?'A · B · A':'B · A · B';return `<div class="weekSeq ${w===S.week?'active':''}"><b>Woche ${w}</b>${seq}</div>`}).join('')}
function openSettings(){dayPick.innerHTML='';DAYS.forEach((name,i)=>dayPick.innerHTML+=`<label><input type="checkbox" value="${i}" ${S.settings.days.includes(i)?'checked':''}> ${name}</label>`);document.querySelectorAll('input[name=level]').forEach(x=>x.checked=x.value===S.settings.level);settings.classList.add('show')}
function closeSettings(){settings.classList.remove('show')}
function saveSettings(){let days=[...document.querySelectorAll('#dayPick input:checked')].map(x=>+x.value);if(!days.length){alert('Bitte mindestens einen Trainingstag auswählen.');return}S.settings.days=days;S.settings.level=document.querySelector('input[name=level]:checked')?.value||'advanced';save();closeSettings();render()}
function resetAll(){if(!confirm('Wirklich ALLE Trainingsdaten löschen und auf Woche 1 zurücksetzen?'))return;let keep={...S.settings};S=def();S.settings=keep;localStorage.setItem('crossbarCoachAzureGlassTestV1',JSON.stringify(S));closeSettings();render();tab('home');alert('Trainingsdaten wurden zurückgesetzt. Profil und Trainingstage bleiben erhalten.')}
function render(){let p=ph(S.week);wn.textContent=S.week;phaseName.textContent=p[0];phaseText.textContent=p[4];weekAdvice.innerHTML='<b>'+p[0]+':</b> '+p[4];weeks.innerHTML='';for(let i=1;i<=8;i++){let b=document.createElement('button');b.textContent=i;b.className=i===S.week?'on':'';b.onclick=()=>{S.week=i;save();render()};weeks.appendChild(b)}renderWork('A');renderWork('B');lib.innerHTML=[...new Set([...A,...B])].map((id,i)=>card(id,'L',i,true)).join('');prs.innerHTML=Object.entries(S.prs).length?Object.entries(S.prs).map(([id,p])=>`<div class="logitem"><b>${E[id]?.short||id}</b><div>${p.band?bandLabel(p.band):'ohne Band'} · ${p.reps} Wdh.</div></div>`).join(''):'<div class="logitem muted">Noch keine PRs.</div>';log.innerHTML=S.logs.length?S.logs.slice(0,30).map(l=>`<div class="logitem"><b>${new Date(l.date).toLocaleDateString('de-DE')} · Workout ${l.workout}</b><div class="meta">Woche ${l.week} · ${l.duration||0} min · Gefühl ${l.feeling||'–'}/5</div></div>`).join(''):'<div class="logitem muted">Noch keine Einheit gespeichert.</div>';energy.value=S.ready.energy;sleep.value=S.ready.sleep;sore.value=S.ready.sore;today();stats();readiness();rec();roadmap();refreshCompletion()}
function downloadJson(obj,name){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function backup(){downloadJson(S,'crossbar-azure-test-backup.json')}
function chatgptReport(){let report={report_type:'Crossbar Coach – Auswertung für ChatGPT',app_version:'3.6-azure-test.1',created_at:new Date().toISOString(),user_context:{age:48,weight_kg:83,goal:'Muskelaufbau',level:S.settings.level,equipment:'Crossbar Ultimate Set'},plan:{current_week:S.week,phase:ph(S.week)[0],next_workout:nextWorkout(),planned_days:S.settings.days.map(d=>DAYS[d])},summary:{sessions:S.logs.length,workout_A:S.logs.filter(x=>x.workout==='A').length,workout_B:S.logs.filter(x=>x.workout==='B').length,total_minutes:S.logs.reduce((a,l)=>a+(l.duration||0),0),current_readiness:S.ready},exercises:{},sessions:S.logs,prs:S.prs,instructions_for_chatgpt:'Bitte analysiere Belastungssteuerung, exakte Varianten, Bandkombinationen, Wiederholungen, RIR, Progression, A/B-Balance und Regeneration. Nutze nur vorhandene Daten.'};for(let id of [...A,...B]){let all=[];for(let l of [...S.logs].reverse()){let ss=l.entries?.[id]?.sets?.filter(x=>doneSet(x)&&x.reps)||[];if(ss.length)all.push({date:l.date,week:l.week,workout:l.workout,sets:ss.map(x=>({reps:+x.reps,band:x.band||null,band_side_kg:x.band?bandSideKg(x.band):null,nominal_total_kg:x.band?bandTotalKg(x.band):null,rir:x.rir==='4+'?4:+x.rir}))})}report.exercises[id]={name:E[id].name,muscle:E[id].muscle,target_reps:E[id].reps,sessions:all.length,history:all,pr:S.prs[id]||null}}downloadJson(report,'crossbar-chatgpt-auswertung-woche-'+S.week+'.json')}
imp.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{S=JSON.parse(r.result);S.settings=S.settings||{days:[1,3,5],level:'advanced'};S.settings.level=S.settings.level||'advanced';S.logs=S.logs||[];S.draft=S.draft||{};S.ready=S.ready||{energy:3,sleep:3,sore:3};rebuildPrs();save();render();alert('Backup importiert.')}catch{alert('Backup konnte nicht gelesen werden.')}};r.readAsText(f)};
let tid,remaining=0;function openTimer(s){remaining=s;timer.classList.add('show');tick();clearInterval(tid);tid=setInterval(()=>{remaining--;tick();if(remaining<=0)clearInterval(tid)},1000)}function tick(){clock.textContent=String(Math.max(0,Math.floor(remaining/60))).padStart(2,'0')+':'+String(Math.max(0,remaining%60)).padStart(2,'0')}function closeTimer(){clearInterval(tid);timer.classList.remove('show')}
function tab(id){document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('on',x.dataset.tab===id));scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));[energy,sleep,sore].forEach(x=>x.oninput=readiness);render();